import type { Metadata } from "next";
import { AlertCircle, ArrowUpRight } from "lucide-react";
import Link from "next/link";

export const metadata: Metadata = { title: "How FBIE works | FBIE", description: "Learn how FBIE plans to define, predict, and verify weather forecast failures, and see the current research status." };

const stages = [
  { number: "01", title: "Capture the forecast", body: "Save each weather forecast exactly as it was issued, including its place, valid time, model source, and lead day." },
  { number: "02", title: "Compare with reality", body: "Match the forecast with quality checked observations. Define a meaningful error threshold for each weather variable." },
  { number: "03", title: "Learn and test", body: "Train a model to estimate failure risk, then test it on untouched later periods and calibrate its probabilities." },
  { number: "04", title: "Explain the warning", body: "Show the possible failure type, forecast signals, and relevant past cases alongside each published result." },
  { number: "05", title: "Verify the result", body: "As observations arrive, record whether the warning was right and report performance over time." },
];

export default function MethodologyPage() {
  return <><section className="page-top"><div className="page-shell"><span className="kicker">HOW IT WORKS</span><h1>Trust comes from <em>being checked.</em></h1><p>FBIE is being built around a simple standard: every risk estimate must have a clear definition, a traceable source, and a measurable outcome.</p></div></section><div className="page-body page-shell"><div className="notice"><AlertCircle size={18} /><div><strong>Current research status</strong>This is a product demonstration. Historical data, trained models, calibrated probabilities, and live forecast warnings are still in development.</div></div><div className="method-grid">{stages.map((stage) => <article className="method-card" key={stage.number}><span className="method-num">{stage.number} / 05</span><h2>{stage.title}</h2><p>{stage.body}</p></article>)}</div><div className="method-long"><div><span className="kicker">DEFINING A “BUST”</span><h2>What counts as a wrong forecast?</h2></div><div><p>The answer depends on the variable, place, season, and lead day. A rainfall miss may mean rain happened when none was forecast, the amount differed substantially, or the rain arrived in a different area. Temperature and wind need their own thresholds.</p><p>Thresholds must be set before evaluation, with forecasts compared to observations over matching times and locations. We will show those definitions with each operational product.</p></div></div><div className="method-long"><div><span className="kicker">RESEARCH ROADMAP</span><h2>What is available today?</h2></div><div className="status-list"><div className="status-row"><div><strong>Product interface</strong><p>Landing page, scenario explorer, method and verification views</p></div><span>Demo</span></div><div className="status-row"><div><strong>Forecast and observation archive</strong><p>Needed to create trustworthy examples and train models</p></div><span>Planned</span></div><div className="status-row"><div><strong>Validated failure risk</strong><p>Requires held out testing against simple reference methods</p></div><span>Planned</span></div><div className="status-row"><div><strong>Published outcomes</strong><p>Warnings paired with verified weather after the event</p></div><span>Planned</span></div></div></div><div className="cta-section" style={{ marginBottom: 0 }}><div><span className="kicker">SEE THE EXPERIENCE</span><h2>Explore a <em>scenario.</em></h2><p>Try the dashboard and see how forecast failure modes will be communicated.</p></div><Link href="/explore" className="button button-light">Open dashboard <ArrowUpRight size={18} /></Link></div></div></>;
}
