import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, CloudRain, Clock3, Compass, MapPin, MoveUpRight, SearchCheck, ShieldCheck, Wind } from "lucide-react";

const signalRows = [
  { label: "Forecast agreement", value: "Do models tell the same story?", icon: <Wind size={17} /> },
  { label: "Forecast movement", value: "Has the outlook changed?", icon: <Compass size={17} /> },
  { label: "Historical accuracy", value: "How did similar days turn out?", icon: <SearchCheck size={17} /> },
];

export default function Home() {
  return <>
    <section className="hero"><div className="hero-grid page-shell"><div className="hero-content"><div className="eyebrow"><span className="eyebrow-pulse" /> WEATHER INTELLIGENCE FOR INDIA</div><h1>Know where your forecast <em>could go wrong.</em></h1><p className="hero-lede">A forecast tells you what might happen. FBIE explores where that forecast could fail, how it might fail, and the evidence behind the warning.</p><div className="hero-actions"><Link href="/explore" className="button button-primary">Explore the demo <ArrowUpRight size={18} /></Link><Link href="/methodology" className="text-link">How it works <ArrowRight size={17} /></Link></div><div className="hero-trust"><span className="line-icon"><ShieldCheck size={18} /></span> Research prototype · Illustrative scenarios are clearly labelled</div></div><div className="hero-visual" aria-label="Illustrative forecast confidence window"><div className="visual-top"><div><span className="micro-label">FORECAST CONFIDENCE WINDOW</span><strong>Mumbai, Maharashtra</strong></div><span className="visual-live"><span /> ILLUSTRATIVE</span></div><div className="visual-main"><div className="visual-radar"><div className="radar-ring ring-one" /><div className="radar-ring ring-two" /><div className="radar-ring ring-three" /><div className="radar-sweep" /><div className="radar-core"><CloudRain size={38} strokeWidth={1.5} /></div><div className="radar-pin pin-one" /><div className="radar-pin pin-two" /><div className="radar-pin pin-three" /><span className="radar-label radar-label-top">TIMING</span><span className="radar-label radar-label-right">LOCATION</span><span className="radar-label radar-label-bottom">INTENSITY</span></div><div className="visual-reading"><span className="micro-label">WHAT COULD CHANGE?</span><h3>The rain could arrive somewhere else.</h3><p>Forecast reliability is about the shape of the error, not just a single number.</p></div></div><div className="visual-bottom"><span><Clock3 size={16} /> Up to 10 forecast days</span><span>Rainfall · Temperature · Wind</span></div></div></div><div className="hero-floor page-shell"><div><span className="floor-kicker">THE CORE IDEA</span><p>From <strong>“Will it rain?”</strong> to <strong>“How much should I trust that forecast?”</strong></p></div><div className="floor-arrow"><MoveUpRight size={25} /></div></div></section>

    <section className="section section-intro page-shell"><div className="section-heading"><span className="kicker">THE BLIND SPOT</span><h2>A forecast can be right about rain and wrong about <em>your rain.</em></h2></div><div className="intro-copy"><p>It can arrive six hours later. Miss your district by 40 km. Or be far heavier than expected. Those differences matter when people make real plans.</p><p>FBIE is being built to surface those possible failure modes in language anyone can use.</p></div></section>

    <section className="section signal-section"><div className="page-shell"><div className="section-head-row"><div><span className="kicker">THE FBIE VIEW</span><h2>One forecast. <em>Three clearer questions.</em></h2></div><Link href="/explore" className="text-link">Try the dashboard <ArrowUpRight size={17} /></Link></div><div className="feature-grid"><article className="feature-card feature-card-dark"><div className="feature-icon"><MapPin size={23} /></div><span className="feature-index">01 / WHERE</span><h3>Where might it fail?</h3><p>Explore a location and lead day to see which forecast deserves a closer look.</p><div className="feature-art map-art"><span className="map-dot a" /><span className="map-dot b" /><span className="map-dot c" /><span className="map-dot d" /><span className="map-contour one" /><span className="map-contour two" /><span className="map-contour three" /></div></article><article className="feature-card"><div className="feature-icon warm"><CloudRain size={23} /></div><span className="feature-index">02 / HOW</span><h3>How could it fail?</h3><p>Separate a timing shift from a location miss or an unexpected amount.</p><div className="failure-stack"><span>Timing shift <b>06h</b></span><span>Location miss <b>↗</b></span><span>Amount difference <b>±</b></span></div></article><article className="feature-card"><div className="feature-icon cool"><SearchCheck size={23} /></div><span className="feature-index">03 / WHY</span><h3>What supports it?</h3><p>Inspect forecast agreement, recent changes, and similar verified cases.</p><div className="mini-signals">{signalRows.map((row) => <div key={row.label}>{row.icon}<span><strong>{row.label}</strong><small>{row.value}</small></span><Check size={15} /></div>)}</div></article></div></div></section>

    <section className="section proof-section page-shell"><div className="proof-copy"><span className="kicker">EVIDENCE, NOT MYSTERY</span><h2>A warning you can <em>check.</em></h2><p>Every future prediction should have a trail: what was forecast, why FBIE flagged it, and what was actually observed. We will publish performance as historical data becomes available.</p><Link href="/history" className="button button-outline">View verification <ArrowUpRight size={18} /></Link></div><div className="proof-panel"><div className="proof-panel-head"><span>THE VERIFICATION LOOP</span><span>01 → 03</span></div><div className="proof-step"><span>01</span><div><strong>Forecast issued</strong><p>Store what the weather model said at the time.</p></div><span className="step-dot blue" /></div><div className="proof-step"><span>02</span><div><strong>Risk explained</strong><p>Show the failure mode and supporting signals.</p></div><span className="step-dot orange" /></div><div className="proof-step"><span>03</span><div><strong>Outcome checked</strong><p>Compare the forecast against observations.</p></div><span className="step-dot green" /></div><div className="proof-panel-foot">An auditable record for every published result.</div></div></section>

    <section className="section audience-section"><div className="page-shell audience-inner"><div><span className="kicker">BUILT FOR DECISIONS</span><h2>Weather is never just weather.</h2></div><div className="audience-list"><div><span>01</span><strong>Farm planning</strong><p>Know when a rain forecast needs a second look before scheduling field work.</p></div><div><span>02</span><strong>Outdoor operations</strong><p>See the kind of forecast error that could affect a site or event.</p></div><div><span>03</span><strong>Everyday plans</strong><p>Understand uncertainty without decoding technical charts.</p></div></div></div></section>

    <section className="cta-section page-shell"><div><span className="kicker">START EXPLORING</span><h2>See the forecast from<br /><em>another angle.</em></h2><p>Explore the product experience now. Live risk estimates will be added after the data and model are validated.</p></div><Link href="/explore" className="button button-light">Open the demo dashboard <ArrowUpRight size={18} /></Link></section>
  </>;
}
