import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, CloudRain, Clock3, Compass, MapPin, MoveUpRight, SearchCheck, ShieldCheck, Wind } from "lucide-react";

const signalRows = [
  { label: "Historical error", value: "How often did similar rainfall forecasts miss?", icon: <Wind size={17} /> },
  { label: "Season and lead day", value: "When was the forecast made?", icon: <Compass size={17} /> },
  { label: "Reference data", value: "What weather record was used?", icon: <SearchCheck size={17} /> },
];

export default function Home() {
  return <>
    <section className="hero"><div className="hero-grid page-shell"><div className="hero-content"><div className="eyebrow"><span className="eyebrow-pulse" /> WEATHER INTELLIGENCE FOR INDIA</div><h1>Know where your forecast <em>could go wrong.</em></h1><p className="hero-lede">FBIE estimates when a daily rainfall forecast may miss a defined error threshold. See published evidence where available, and a clear no-data state everywhere else.</p><div className="hero-actions"><Link href="/explore" className="button button-primary">Explore the dashboard <ArrowUpRight size={18} /></Link><Link href="/methodology" className="text-link">How it works <ArrowRight size={17} /></Link></div><div className="hero-trust"><span className="line-icon"><ShieldCheck size={18} /></span> Rainfall research baseline · Illustrative scenarios are labelled</div></div><div className="hero-visual" aria-label="Illustrative forecast confidence window"><div className="visual-top"><div><span className="micro-label">FORECAST CONFIDENCE WINDOW</span><strong>Mumbai, Maharashtra</strong></div><span className="visual-live"><span /> ILLUSTRATIVE</span></div><div className="visual-main"><div className="visual-radar"><div className="radar-ring ring-one" /><div className="radar-ring ring-two" /><div className="radar-ring ring-three" /><div className="radar-sweep" /><div className="radar-core"><CloudRain size={38} strokeWidth={1.5} /></div><div className="radar-pin pin-one" /><div className="radar-pin pin-two" /><div className="radar-pin pin-three" /><span className="radar-label radar-label-top">LEAD DAY</span><span className="radar-label radar-label-right">SEASON</span><span className="radar-label radar-label-bottom">AMOUNT</span></div><div className="visual-reading"><span className="micro-label">WHAT COULD CHANGE?</span><h3>Could the rainfall amount miss?</h3><p>The first baseline measures daily rainfall amount error against a declared threshold.</p></div></div><div className="visual-bottom"><span><Clock3 size={16} /> Up to 10 forecast days</span><span>Rainfall baseline · More variables planned</span></div></div></div><div className="hero-floor page-shell"><div><span className="floor-kicker">THE CORE IDEA</span><p>From <strong>“Will it rain?”</strong> to <strong>“How much should I trust that forecast?”</strong></p></div><div className="floor-arrow"><MoveUpRight size={25} /></div></div></section>

    <section className="section section-intro page-shell"><div className="section-heading"><span className="kicker">THE BLIND SPOT</span><h2>A forecast can be right about rain and wrong about <em>your rain.</em></h2></div><div className="intro-copy"><p>Rainfall amount can be far above or below a forecast. The first research baseline measures that error against a declared threshold. Timing and location misses are later research targets.</p><p>The dashboard labels which results are published and which selections have no measured estimate.</p></div></section>

    <section className="section signal-section"><div className="page-shell"><div className="section-head-row"><div><span className="kicker">THE FBIE VIEW</span><h2>One forecast. <em>Three useful checks.</em></h2></div><Link href="/explore" className="text-link">Try the dashboard <ArrowUpRight size={17} /></Link></div><div className="feature-grid"><article className="feature-card feature-card-dark"><div className="feature-icon"><MapPin size={23} /></div><span className="feature-index">01 / WHERE</span><h3>Where is risk available?</h3><p>Choose a place and lead day. Measured risk appears only for approved, published results.</p><div className="feature-art map-art"><span className="map-dot a" /><span className="map-dot b" /><span className="map-dot c" /><span className="map-dot d" /><span className="map-contour one" /><span className="map-contour two" /><span className="map-contour three" /></div></article><article className="feature-card"><div className="feature-icon warm"><CloudRain size={23} /></div><span className="feature-index">02 / HOW</span><h3>What counts as a miss?</h3><p>The first baseline tests whether daily rainfall amount error exceeds a defined threshold.</p><div className="failure-stack"><span>Daily rainfall <b>mm</b></span><span>Error threshold <b>±</b></span><span>Lead day <b>D1–10</b></span></div></article><article className="feature-card"><div className="feature-icon cool"><SearchCheck size={23} /></div><span className="feature-index">03 / WHY</span><h3>What supports the estimate?</h3><p>Inspect historical rate signals, source and model details, and available reference outcomes.</p><div className="mini-signals">{signalRows.map((row) => <div key={row.label}>{row.icon}<span><strong>{row.label}</strong><small>{row.value}</small></span><Check size={15} /></div>)}</div></article></div></div></section>

    <section className="section proof-section page-shell"><div className="proof-copy"><span className="kicker">EVIDENCE, NOT MYSTERY</span><h2>A warning you can <em>check.</em></h2><p>Published estimates carry their forecast source, model version, and issue time. Historical comparisons state whether the reference is an observation or ERA5 reanalysis proxy.</p><Link href="/history" className="button button-outline">View verification <ArrowUpRight size={18} /></Link></div><div className="proof-panel"><div className="proof-panel-head"><span>THE VERIFICATION LOOP</span><span>01 → 03</span></div><div className="proof-step"><span>01</span><div><strong>Forecast issued</strong><p>Store what the weather model said at the time.</p></div><span className="step-dot blue" /></div><div className="proof-step"><span>02</span><div><strong>Risk explained</strong><p>Show the rainfall error threshold and source.</p></div><span className="step-dot orange" /></div><div className="proof-step"><span>03</span><div><strong>Outcome checked</strong><p>Compare with labelled reference data.</p></div><span className="step-dot green" /></div><div className="proof-panel-foot">A traceable record for each published result.</div></div></section>

    <section className="section audience-section"><div className="page-shell audience-inner"><div><span className="kicker">BUILT FOR DECISIONS</span><h2>Weather is never just weather.</h2></div><div className="audience-list"><div><span>01</span><strong>Farm planning</strong><p>Review a published rainfall risk estimate before scheduling field work.</p></div><div><span>02</span><strong>Outdoor operations</strong><p>Review rainfall amount uncertainty for supported places and days.</p></div><div><span>03</span><strong>Everyday plans</strong><p>See when measured risk is available and when it is not.</p></div></div></div></section>

    <section className="cta-section page-shell"><div><span className="kicker">START EXPLORING</span><h2>See the forecast from<br /><em>another angle.</em></h2><p>Explore the product now. Published estimates appear where approved data exists; other selections stay clearly labelled.</p></div><Link href="/explore" className="button button-light">Open the dashboard <ArrowUpRight size={18} /></Link></section>
  </>;
}
